spring:
  application:
    name: startup

  datasource:
#    jdbc-url: jdbc:postgresql://localhost/spring-microservices
    url: jdbc:postgresql://localhost:5432/spring-microservices
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
#       dialect: org.hibernate.dialect.PostgreSQLDialect
       format_sql: true
    open-in-view: false