server:
  port: 8100

spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:postgresql://localhost:5432/book-service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      #      naming:
      #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        #       dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: true
  flyway:
    url: jdbc:postgresql://localhost:5432/book-service
    schemas: book_service # exchange-service
    user: postgres
    password: postgres
