server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 5
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true

spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
  datasource:
    url: jdbc:postgresql://localhost:5432/book-service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      #      naming:
      #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        #       dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: true
  flyway:
    url: jdbc:postgresql://localhost:5432/book-service
    schemas: book_service # exchange-service
    user: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'