spring:
  application:
    name: greeting-service
    mandatory-file-encoding: UTF-8
    http:
      encoding:
        charset: UTF-8
        enabled: true

  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      profile: dev
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
